### ISSUE TITLE
Post Categories

### ISSUE THREAD

**Issue by ghost** [bitmand/utterson#13]
Feature request.

Categories and ability to display them.

**Comment by bitmand** [comment]
Categories / Category: http://jekyllrb.com/docs/frontmatter/#predefined-global-variables

**Comment by ghost** [comment]
Great - would be nice to be able to choose/make the category in the "Back End"

**Comment by bitmand** [comment]
Took a stab at this and created a page for add, removing and "creating" new categories. Button is on the "Post edit"-page.

Merged into master and closing this feature request.

**Comment by ghost** [comment]
Fantastic.
