### ISSUE TITLE
Error on bundle install --path vendor/bundle

### ISSUE THREAD

**Issue by elenaramirez** [bitmand/utterson#28]
Hi!

I would like to test your plugin for jekyll but when i try to run bundle install --path vendor/bundle i've this error: 

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'bundler' (>= 0) among 50 total gem(s) (Gem::LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in`to_spec'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
    from /usr/local/bin/bundle:22:in`<main>'

I've upgraded ruby but nothin changes. 

Could anyone help me?

**Comment by bitmand** [comment]
@elenaramirez try installing bundler first, with the command: `gem install bundler` ( more info on bundler itself on: http://bundler.io ) and then run `bundle install --path vendor/bundle` afterwards.
